#+TITLE: API: =rtb_log.h=
#+AUTHOR: Robert Coffey
#+OPTIONS: toc:nil

** Introduction

Macros for printing to the stderr stream.

** Usage

For default behaviour, include =rtb_log.h= in each compilation unit that is to
have access to the logging macros.
#+BEGIN_SRC C
#include "rtb_log.h"
#+END_SRC

Define the ~RTB_NO_EXIT~ macro before including =rtb_log.h= to prevent the
~elog~ macros from calling ~exit~.
#+BEGIN_SRC C
#define RTB_NO_EXIT
#include "rtb_log.h"
#+END_SRC

** Macros

Print without formatting:
- [[*=rtb_log=]] =rtb_log=
- [[*=rtb_ilog=]] =rtb_ilog=
- [[*=rtb_wlog=]] =rtb_wlog=
- [[*=rtb_elog=]] =rtb_elog=

Print with C-style formatting:
- [[*=rtb_logf=]] =rtb_logf=
- [[*=rtb_ilogf=]] =rtb_ilogf=
- [[*=rtb_wlogf=]] =rtb_wlogf=
- [[*=rtb_elogf=]] =rtb_elogf=

-----

*** =rtb_log=

**** Synopsis
#+BEGIN_SRC C
#define rtb_log(X)
#+END_SRC

**** Arguments
- ~X~: C-style string

**** Description
Print a string to the stderr stream, ending the current line.

-----

*** =rtb_ilog=

**** Synopsis
#+BEGIN_SRC C
#define rtb_ilog(X)
#+END_SRC

**** Arguments
- ~X~: C-style string

**** Description
Print a string to the stderr stream with the preamble "Info: ", ending the
current line.

-----

*** =rtb_wlog=

**** Synopsis
#+BEGIN_SRC C
#define rtb_wlog(X)
#+END_SRC

**** Arguments
- ~X~: C-style string

**** Description
Print a string to the stderr stream with the preamble "Warning: ", ending the
current line.

-----

*** =rtb_elog=

**** Synopsis
#+BEGIN_SRC C
#define rtb_elog(X)
#+END_SRC

**** Arguments
- ~X~: C-style string

**** Description
Print a string to the stderr stream with the preamble "Error: ", ending the
current line.

This macro will also exit the program, unless ~RTB_NO_EXIT~ was defined before
including =rtb_log.h=.

-----

*** =rtb_logf=

**** Synopsis
#+BEGIN_SRC C
#define rtb_logf(...)
#+END_SRC

**** Arguments
- ~...~: Variadic argument

**** Description
Print a formatted string to the stderr stream. Passes the variadic argument
directly to ~fprintf~.

-----

*** =rtb_ilogf=

**** Synopsis
#+BEGIN_SRC C
#define rtb_ilogf(...)
#+END_SRC

**** Arguments
- ~...~: Variadic argument

**** Description
Print a formatted string to the stderr stream with the preamble "Info: ". Passes
the variadic argument directly to ~fprintf~.

-----

*** =rtb_wlogf=

**** Synopsis
#+BEGIN_SRC C
#define rtb_wlogf(...)
#+END_SRC

**** Arguments
- ~...~: Variadic argument

**** Description
Print a formatted string to the stderr stream with the preamble
"Warning: ". Passes the variadic argument directly to ~fprintf~.

-----

*** =rtb_elogf=

**** Synopsis
#+BEGIN_SRC C
#define rtb_wlogf(...)
#+END_SRC

**** Arguments
- ~...~: Variadic argument

**** Description
Print a formatted string to the stderr stream with the preamble
"Error: ". Passes the variadic argument directly to ~fprintf~.

This macro will also exit the program, unless ~RTB_NO_EXIT~ was defined before
including =rtb_log.h=.

-----
